// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkFinderAPI.Models;

#nullable disable

namespace ParkFinderAPI.Migrations
{
    [DbContext(typeof(ParkFinderAPIContext))]
    [Migration("20231125165901_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParkFinderAPI.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Name = "Yellowstone",
                            State = "Montana",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 2,
                            Name = "Crater Lake",
                            State = "Oregon",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 3,
                            Name = "Cape Lookout",
                            State = "Oregon",
                            Type = "State Park"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
